/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/dashboard/categories/index'
import { Route as DashboardProductsNewRouteImport } from './routes/dashboard/products/new'
import { Route as DashboardProductsIdRouteImport } from './routes/dashboard/products/$id'
import { Route as DashboardCategoriesNewRouteImport } from './routes/dashboard/categories/new'
import { Route as DashboardCategoriesIdRouteImport } from './routes/dashboard/categories/$id'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsIdRoute = DashboardProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesNewRoute = DashboardCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesIdRoute = DashboardCategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/categories/$id': typeof DashboardCategoriesIdRoute
  '/dashboard/categories/new': typeof DashboardCategoriesNewRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/categories/$id': typeof DashboardCategoriesIdRoute
  '/dashboard/categories/new': typeof DashboardCategoriesNewRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/categories/$id': typeof DashboardCategoriesIdRoute
  '/dashboard/categories/new': typeof DashboardCategoriesNewRoute
  '/dashboard/products/$id': typeof DashboardProductsIdRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/categories/$id'
    | '/dashboard/categories/new'
    | '/dashboard/products/$id'
    | '/dashboard/products/new'
    | '/dashboard/categories/'
    | '/dashboard/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/categories/$id'
    | '/dashboard/categories/new'
    | '/dashboard/products/$id'
    | '/dashboard/products/new'
    | '/dashboard/categories'
    | '/dashboard/products'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/categories/$id'
    | '/dashboard/categories/new'
    | '/dashboard/products/$id'
    | '/dashboard/products/new'
    | '/dashboard/categories/'
    | '/dashboard/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/new': {
      id: '/dashboard/products/new'
      path: '/products/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/$id': {
      id: '/dashboard/products/$id'
      path: '/products/$id'
      fullPath: '/dashboard/products/$id'
      preLoaderRoute: typeof DashboardProductsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories/new': {
      id: '/dashboard/categories/new'
      path: '/categories/new'
      fullPath: '/dashboard/categories/new'
      preLoaderRoute: typeof DashboardCategoriesNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories/$id': {
      id: '/dashboard/categories/$id'
      path: '/categories/$id'
      fullPath: '/dashboard/categories/$id'
      preLoaderRoute: typeof DashboardCategoriesIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCategoriesIdRoute: typeof DashboardCategoriesIdRoute
  DashboardCategoriesNewRoute: typeof DashboardCategoriesNewRoute
  DashboardProductsIdRoute: typeof DashboardProductsIdRoute
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCategoriesIdRoute: DashboardCategoriesIdRoute,
  DashboardCategoriesNewRoute: DashboardCategoriesNewRoute,
  DashboardProductsIdRoute: DashboardProductsIdRoute,
  DashboardProductsNewRoute: DashboardProductsNewRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
